version: '3.7'
services:
  sqlserver:
    container_name: sqlserver2019
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: Admin12345
      ACCEPT_EULA: Y
    volumes:
      - ./data:/var/opt/mssql
